export const data = [
  {
    id: 1,
    image: 'assets/trending/58.jpg',
    category: 'Headphones',
    productName: 'Wireless Bluetooth Headphones',
    price: 198.5,
    onSale: false,
    oldPrice: null,
    countInStock: 18,
  },
  {
    id: 2,
    image: 'assets/trending/59.jpg',
    category: 'Computers',
    productName: 'AirPort Extreme Base Station',
    price: 98.99,
    onSale: true,
    oldPrice: 149.99,
    countInStock: 6,
  },
  {
    id: 3,
    image: 'assets/trending/60.jpg',
    category: 'TV, Video & Audio',
    productName: 'Smart TV LED 49’ Ultra HD',
    price: 149.99,
    onSale: false,
    oldPrice: null,
    countInStock: 0,
  },
  {
    id: 4,
    image: 'assets/trending/61.jpg',
    category: 'Smart Home',
    productName: 'Smart Speaker with Voice Control',
    price: 49.99,
    onSale: false,
    oldPrice: null,
    countInStock: 12,
  },
  {
    id: 5,
    image: 'assets/trending/62.jpg',
    category: 'Wearable Electronics',
    productName: 'Fitness GPS Smart Watch',
    price: 149.99,
    onSale: false,
    oldPrice: null,
    countInStock: 3,
  },
  {
    id: 6,
    image: 'assets/trending/63.jpg',
    category: 'Smartphones',
    productName: 'Popular Smartphone',
    price: 969.99,
    onSale: false,
    oldPrice: null,
    countInStock: 5,
  },
  {
    id: 7,
    image: 'assets/trending/64.jpg',
    category: 'Wearable Electronics',
    productName: 'Smart Watch Series 5, Aluminium',
    price: 349.99,
    onSale: false,
    oldPrice: null,
    countInStock: 9,
  },
  {
    id: 8,
    image: 'assets/trending/65.jpg',
    category: 'Computers',
    productName: 'Convertible 2-in-1 Laptop',
    price: 149.99,
    onSale: false,
    oldPrice: null,
    countInStock: 4,
  },
];
